### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by EliaGeretto** [seemoo-lab/toothpicker#1]
Thanks for open sourcing this project! I think many different parties would greatly benefit if you could specify a license, as having no license makes things harder for e.g. academic and/or industry researchers who would like to use this tool and expand upon this research.

**Comment by jiska2342** [comment]
Hi,

thanks for asking :) The issue is that the *frizzer* project, on which *ToothPicker* is based, did not specify any license. As we know the authors of that project we're currently waiting for their feedback and will then update our license accordingly.

**Comment by ttdennis** [comment]
I just pushed the license. Thanks for raising the issue :)
