### ISSUE TITLE
AttributeError: 'int' object has no attribute 'upper'

### ISSUE THREAD

**Issue by vaibhvbedi** [seemoo-lab/toothpicker#4]
Hi All,

I am running the MagicPairingFuzzer.py..
If I am running with the internalblue python2 version.. I'm getting this error.
![image](https://user-images.githubusercontent.com/50806170/117651576-ac753180-b1c4-11eb-8c38-057f3a565db4.png)

If I am running with the internalblue python3 version. I'm getting this error.

![image](https://user-images.githubusercontent.com/50806170/117651520-9a938e80-b1c4-11eb-85c2-dfefb2e64f36.png)

Please Let me know How I can solve this error. What's the appropriate version of python for the OTA fuzzer.

Thank you so much in advance.

**Comment by ttdennis** [comment]
Hi, `internalblue` and the `MagicPairingFuzzer.py` requires python3. The problems should be gone when you try python3.

**Comment by vaibhvbedi** [comment]
Hi, @ttdennis If I am using internalBlue and MagicFuzzer python3 version then getting this error.


![image](https://user-images.githubusercontent.com/50806170/117869466-6952b580-b2cd-11eb-9545-63fa3d3fe451.png)

**Comment by ttdennis** [comment]
Ah right, there was a change in the log level handling. I just pushed an update, it should work now.

**Comment by vaibhvbedi** [comment]
Hi, Thanks for your reply. Now I am getting the another issue and I don't know which file is missing 
![image](https://user-images.githubusercontent.com/50806170/117871365-e0894900-b2cf-11eb-8f9e-de7c02948263.png)

**Comment by ttdennis** [comment]
Did you properly install [internalblue](https://github.com/seemoo-lab/internalblue)? It seems like it tries to connect to an iOS device running the internalblue proxy but the connection does not seem to be successful.

**Comment by vaibhvbedi** [comment]
Thanks for your help @ttdennis.
